import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import('file:///C:/Users/senm1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const base=process.env.TEST_BASE_URL||'http://localhost:3199',out=process.env.TEST_ARTIFACT_DIR||'docs/cilindros-premium/benchmark';await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});const results=[];
try{for(const width of [1440,1024,768,390,320]){
 const c=await browser.newContext({viewport:{width,height:width===390?844:width===320?740:1000}});await c.route('https://cloud.umami.is/**',r=>r.abort());const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/cilindros-neumaticos');await p.locator('.industrial-stage.is-ready').waitFor();await p.waitForTimeout(1600);const stage=p.locator('.cylinder-sticky'),experience=p.locator('.cylinder-experience');await stage.screenshot({path:`${out}/ensamblado-${width}.png`});
 await experience.evaluate(el=>{const sticky=el.querySelector('.cylinder-sticky');window.scrollTo({top:el.getBoundingClientRect().top+scrollY-parseFloat(getComputedStyle(sticky).top)+(el.clientHeight-sticky.clientHeight)*.55,behavior:'instant'});});await p.waitForTimeout(1800);assert.equal(await experience.getAttribute('data-phase'),'1');await stage.screenshot({path:`${out}/exploded-${width}.png`});
 await p.getByRole('button',{name:/Pist/}).click();await p.waitForTimeout(800);await stage.screenshot({path:`${out}/seleccion-${width}.png`});assert.ok((await p.getByRole('status').innerText()).includes('Recibe la presión'));
 await p.getByRole('button',{name:/Pist/}).click();await p.getByRole('button',{name:'Ensamblar',exact:true}).click();await p.waitForTimeout(1900);assert.equal(await p.getByRole('button',{name:'Explorar el interior',exact:true}).getAttribute('aria-pressed'),'false');
 await experience.evaluate(el=>{const sticky=el.querySelector('.cylinder-sticky');window.scrollTo({top:el.getBoundingClientRect().top+scrollY-parseFloat(getComputedStyle(sticky).top)+(el.clientHeight-sticky.clientHeight)*.95,behavior:'instant'});});await p.waitForTimeout(1400);assert.equal(await experience.getAttribute('data-phase'),'2');assert.ok(await p.getByRole('link',{name:'Hablemos de tu cilindro'}).isVisible());
 const frames=await p.locator('.stage-canvas').getAttribute('data-rendered-frames');await p.waitForTimeout(500);assert.equal(await p.locator('.stage-canvas').getAttribute('data-rendered-frames'),frames);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);results.push({width,errors,scrollChapters:3,selection:true,manualOverride:true,idleRenderer:true,overflow:false});await c.close();}
 for(const mode of ['no-js','reduced-motion','context-loss']){
 const c=await browser.newContext({viewport:{width:390,height:844},javaScriptEnabled:mode!=='no-js',reducedMotion:mode==='reduced-motion'?'reduce':'no-preference'});await c.route('https://cloud.umami.is/**',r=>r.abort());const p=await c.newPage();await p.goto(base+'/cilindros-neumaticos');
 if(mode==='context-loss'){await p.locator('.industrial-stage.is-ready').waitFor();await p.locator('canvas').evaluate(el=>el.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await p.waitForTimeout(500);assert.equal(await p.locator('.industrial-stage.is-ready').count(),0);}else assert.equal(await p.locator('canvas').count(),0);
 assert.ok(await p.getByRole('heading',{level:1}).isVisible());assert.ok(await p.locator('.cylinder-experience').getByRole('link',{name:'Solicitar cotización',exact:true}).isVisible());assert.ok(await p.locator('.stage-fallback img').evaluate(el=>el.complete&&el.naturalWidth>0));assert.equal(await p.locator('.cylinder-experience').getAttribute('data-phase'),'0');results.push({fallback:mode,contentAndCtaVisible:true});await c.close();
 }
 await writeFile(`${out}/pruebas.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results));}finally{await browser.close();}
